sudo: required
language: node_js
node_js:
  - 8

services:
  - docker
  
branches:
  only:
  - master

script:
  - npm test
  - npm run build
  - docker build -t nukeop/tinycrawl-backend .

deploy:
  provider: script
  script: bash docker_push
  skip_cleanup: true
  on:
    branch: master
