sudo: required
language: node_js
node_js:
  - 8

services:
  - docker
  
branches:
  only:
  - master

script:
  - npm test
  - docker build -t nukeop/tinycrawl-backend .
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t nukeop/tinycrawl-backend-rpi -f Dockerfile_arm .

deploy:
  provider: script
  script: bash docker_push
  skip_cleanup: true
  on:
    branch: master
