FROM arm32v7/node:8

WORKDIR /usr/app

COPY ./dist/. /usr/app/dist
COPY ./package.json /usr/app

RUN npm install --only=production && npm cache clean --force

ARG PORT=80
ENV PORT ${PORT}

CMD npm run server

EXPOSE $PORT
