#!/bin/bash
git config core.sshCommand "ssh -i .travis/deploy.key"
git stash --all
git checkout master
cp .travis/config.js server
git add server/config.js
git commit -m "update config.js"
git push -f deploy master
